# Generated by Django 4.0.3 on 2022-03-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Name',
            name='age',
            field=models.IntegerField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
