# Generated by Django 4.0.3 on 2022-03-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0003_details_alter_name_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
