# Generated by Django 4.0.3 on 2022-04-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0006_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
    ]
